package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsProject<M extends BaseGoodsProject<M>> extends Model<M> implements IBean {

	public void setGoods(java.lang.Long goods) {
		set("goods", goods);
	}

	public java.lang.Long getGoods() {
		return get("goods");
	}

	public void setProjects(java.lang.Long projects) {
		set("projects", projects);
	}

	public java.lang.Long getProjects() {
		return get("projects");
	}

}
