package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsPromotion<M extends BaseGoodsPromotion<M>> extends Model<M> implements IBean {

	public void setGoods(java.lang.Long goods) {
		set("goods", goods);
	}

	public java.lang.Long getGoods() {
		return get("goods");
	}

	public void setPromotions(java.lang.Long promotions) {
		set("promotions", promotions);
	}

	public java.lang.Long getPromotions() {
		return get("promotions");
	}

}
