package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShippingPaymentMethod<M extends BaseShippingPaymentMethod<M>> extends Model<M> implements IBean {

	public void setShippingMethods(java.lang.Long shippingMethods) {
		set("shipping_methods", shippingMethods);
	}

	public java.lang.Long getShippingMethods() {
		return get("shipping_methods");
	}

	public void setPaymentMethods(java.lang.Long paymentMethods) {
		set("payment_methods", paymentMethods);
	}

	public java.lang.Long getPaymentMethods() {
		return get("payment_methods");
	}

}
