package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setAttributeValue0(String attributeValue0) {
		set("attribute_value0", attributeValue0);
	}

	public String getAttributeValue0() {
		return get("attribute_value0");
	}

	public void setAttributeValue1(String attributeValue1) {
		set("attribute_value1", attributeValue1);
	}

	public String getAttributeValue1() {
		return get("attribute_value1");
	}

	public void setAttributeValue10(String attributeValue10) {
		set("attribute_value10", attributeValue10);
	}

	public String getAttributeValue10() {
		return get("attribute_value10");
	}

	public void setAttributeValue11(String attributeValue11) {
		set("attribute_value11", attributeValue11);
	}

	public String getAttributeValue11() {
		return get("attribute_value11");
	}

	public void setAttributeValue12(String attributeValue12) {
		set("attribute_value12", attributeValue12);
	}

	public String getAttributeValue12() {
		return get("attribute_value12");
	}

	public void setAttributeValue13(String attributeValue13) {
		set("attribute_value13", attributeValue13);
	}

	public String getAttributeValue13() {
		return get("attribute_value13");
	}

	public void setAttributeValue14(String attributeValue14) {
		set("attribute_value14", attributeValue14);
	}

	public String getAttributeValue14() {
		return get("attribute_value14");
	}

	public void setAttributeValue15(String attributeValue15) {
		set("attribute_value15", attributeValue15);
	}

	public String getAttributeValue15() {
		return get("attribute_value15");
	}

	public void setAttributeValue16(String attributeValue16) {
		set("attribute_value16", attributeValue16);
	}

	public String getAttributeValue16() {
		return get("attribute_value16");
	}

	public void setAttributeValue17(String attributeValue17) {
		set("attribute_value17", attributeValue17);
	}

	public String getAttributeValue17() {
		return get("attribute_value17");
	}

	public void setAttributeValue18(String attributeValue18) {
		set("attribute_value18", attributeValue18);
	}

	public String getAttributeValue18() {
		return get("attribute_value18");
	}

	public void setAttributeValue19(String attributeValue19) {
		set("attribute_value19", attributeValue19);
	}

	public String getAttributeValue19() {
		return get("attribute_value19");
	}

	public void setAttributeValue2(String attributeValue2) {
		set("attribute_value2", attributeValue2);
	}

	public String getAttributeValue2() {
		return get("attribute_value2");
	}

	public void setAttributeValue3(String attributeValue3) {
		set("attribute_value3", attributeValue3);
	}

	public String getAttributeValue3() {
		return get("attribute_value3");
	}

	public void setAttributeValue4(String attributeValue4) {
		set("attribute_value4", attributeValue4);
	}

	public String getAttributeValue4() {
		return get("attribute_value4");
	}

	public void setAttributeValue5(String attributeValue5) {
		set("attribute_value5", attributeValue5);
	}

	public String getAttributeValue5() {
		return get("attribute_value5");
	}

	public void setAttributeValue6(String attributeValue6) {
		set("attribute_value6", attributeValue6);
	}

	public String getAttributeValue6() {
		return get("attribute_value6");
	}

	public void setAttributeValue7(String attributeValue7) {
		set("attribute_value7", attributeValue7);
	}

	public String getAttributeValue7() {
		return get("attribute_value7");
	}

	public void setAttributeValue8(String attributeValue8) {
		set("attribute_value8", attributeValue8);
	}

	public String getAttributeValue8() {
		return get("attribute_value8");
	}

	public void setAttributeValue9(String attributeValue9) {
		set("attribute_value9", attributeValue9);
	}

	public String getAttributeValue9() {
		return get("attribute_value9");
	}

	public void setCaption(String caption) {
		set("caption", caption);
	}

	public String getCaption() {
		return get("caption");
	}

	public void setGenerateMethod(Integer generateMethod) {
		set("generate_method", generateMethod);
	}

	public Integer getGenerateMethod() {
		return get("generate_method");
	}

	public void setHits(Long hits) {
		set("hits", hits);
	}

	public Long getHits() {
		return get("hits");
	}

	public void setImage(String image) {
		set("image", image);
	}

	public String getImage() {
		return get("image");
	}

	public void setIntroduction(String introduction) {
		set("introduction", introduction);
	}

	public String getIntroduction() {
		return get("introduction");
	}

	public void setIsDelivery(Boolean isDelivery) {
		set("is_delivery", isDelivery);
	}

	public Boolean getIsDelivery() {
		return get("is_delivery");
	}

	public void setIsList(Boolean isList) {
		set("is_list", isList);
	}

	public Boolean getIsList() {
		return get("is_list");
	}

	public void setIsMarketable(Boolean isMarketable) {
		set("is_marketable", isMarketable);
	}

	public Boolean getIsMarketable() {
		return get("is_marketable");
	}

	public void setIsTop(Boolean isTop) {
		set("is_top", isTop);
	}

	public Boolean getIsTop() {
		return get("is_top");
	}

	public void setKeyword(String keyword) {
		set("keyword", keyword);
	}

	public String getKeyword() {
		return get("keyword");
	}

	public void setMarketPrice(java.math.BigDecimal marketPrice) {
		set("market_price", marketPrice);
	}

	public java.math.BigDecimal getMarketPrice() {
		return get("market_price");
	}

	public void setChannel(String channel) {
		set("channel", channel);
	}

	public String getChannel() {
		return get("channel");
	}

	public void setMonthHits(Long monthHits) {
		set("month_hits", monthHits);
	}

	public Long getMonthHits() {
		return get("month_hits");
	}

	public void setMonthHitsDate(java.util.Date monthHitsDate) {
		set("month_hits_date", monthHitsDate);
	}

	public java.util.Date getMonthHitsDate() {
		return get("month_hits_date");
	}

	public void setMonthSales(Long monthSales) {
		set("month_sales", monthSales);
	}

	public Long getMonthSales() {
		return get("month_sales");
	}

	public void setMonthSalesDate(java.util.Date monthSalesDate) {
		set("month_sales_date", monthSalesDate);
	}

	public java.util.Date getMonthSalesDate() {
		return get("month_sales_date");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setParameterValues(String parameterValues) {
		set("parameter_values", parameterValues);
	}

	public String getParameterValues() {
		return get("parameter_values");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setProductImages(String productImages) {
		set("product_images", productImages);
	}

	public String getProductImages() {
		return get("product_images");
	}

	public void setSales(Long sales) {
		set("sales", sales);
	}

	public Long getSales() {
		return get("sales");
	}

	public void setScore(Float score) {
		set("score", score);
	}

	public Float getScore() {
		return get("score");
	}

	public void setScoreCount(Long scoreCount) {
		set("score_count", scoreCount);
	}

	public Long getScoreCount() {
		return get("score_count");
	}

	public void setSeoDescription(String seoDescription) {
		set("seo_description", seoDescription);
	}

	public String getSeoDescription() {
		return get("seo_description");
	}

	public void setSeoKeywords(String seoKeywords) {
		set("seo_keywords", seoKeywords);
	}

	public String getSeoKeywords() {
		return get("seo_keywords");
	}

	public void setSeoTitle(String seoTitle) {
		set("seo_title", seoTitle);
	}

	public String getSeoTitle() {
		return get("seo_title");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setSpecificationItems(String specificationItems) {
		set("specification_items", specificationItems);
	}

	public String getSpecificationItems() {
		return get("specification_items");
	}

	public void setTotalScore(Long totalScore) {
		set("total_score", totalScore);
	}

	public Long getTotalScore() {
		return get("total_score");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setUnit(String unit) {
		set("unit", unit);
	}

	public String getUnit() {
		return get("unit");
	}

	public void setWeekHits(Long weekHits) {
		set("week_hits", weekHits);
	}

	public Long getWeekHits() {
		return get("week_hits");
	}

	public void setWeekHitsDate(java.util.Date weekHitsDate) {
		set("week_hits_date", weekHitsDate);
	}

	public java.util.Date getWeekHitsDate() {
		return get("week_hits_date");
	}

	public void setWeekSales(Long weekSales) {
		set("week_sales", weekSales);
	}

	public Long getWeekSales() {
		return get("week_sales");
	}

	public void setWeekSalesDate(java.util.Date weekSalesDate) {
		set("week_sales_date", weekSalesDate);
	}

	public java.util.Date getWeekSalesDate() {
		return get("week_sales_date");
	}

	public void setWeight(Integer weight) {
		set("weight", weight);
	}

	public Integer getWeight() {
		return get("weight");
	}

	public void setBrandId(Long brandId) {
		set("brand_id", brandId);
	}

	public Long getBrandId() {
		return get("brand_id");
	}

	public void setProductCategoryId(Long productCategoryId) {
		set("product_category_id", productCategoryId);
	}

	public Long getProductCategoryId() {
		return get("product_category_id");
	}

}
