package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsTag<M extends BaseGoodsTag<M>> extends Model<M> implements IBean {

	public void setGoods(java.lang.Long goods) {
		set("goods", goods);
	}

	public java.lang.Long getGoods() {
		return get("goods");
	}

	public void setTags(java.lang.Long tags) {
		set("tags", tags);
	}

	public java.lang.Long getTags() {
		return get("tags");
	}

}
