package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberFavoriteGoods<M extends BaseMemberFavoriteGoods<M>> extends Model<M> implements IBean {

	public void setFavoriteMembers(java.lang.Long favoriteMembers) {
		set("favorite_members", favoriteMembers);
	}

	public java.lang.Long getFavoriteMembers() {
		return get("favorite_members");
	}

	public void setFavoriteGoods(java.lang.Long favoriteGoods) {
		set("favorite_goods", favoriteGoods);
	}

	public java.lang.Long getFavoriteGoods() {
		return get("favorite_goods");
	}

}
