package com.jfinalshop.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ad", "id", Ad.class);
		arp.addMapping("ad_position", "id", AdPosition.class);
		arp.addMapping("admin", "id", Admin.class);
		// Composite Primary Key order: admins,roles
		arp.addMapping("admin_role", "admins,roles", AdminRole.class);
		arp.addMapping("area", "id", Area.class);
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("article_category", "id", ArticleCategory.class);
		// Composite Primary Key order: articles,tags
		arp.addMapping("article_tag", "articles,tags", ArticleTag.class);
		arp.addMapping("attribute", "id", Attribute.class);
		arp.addMapping("brand", "id", Brand.class);
		arp.addMapping("cart", "id", Cart.class);
		arp.addMapping("cart_item", "id", CartItem.class);
		arp.addMapping("consultation", "id", Consultation.class);
		arp.addMapping("coupon", "id", Coupon.class);
		arp.addMapping("coupon_code", "id", CouponCode.class);
		arp.addMapping("delivery_center", "id", DeliveryCenter.class);
		arp.addMapping("delivery_corp", "id", DeliveryCorp.class);
		arp.addMapping("delivery_template", "id", DeliveryTemplate.class);
		arp.addMapping("deposit_log", "id", DepositLog.class);
		arp.addMapping("feedback", "id", Feedback.class);
		arp.addMapping("freight_config", "id", FreightConfig.class);
		arp.addMapping("friend_link", "id", FriendLink.class);
		arp.addMapping("goods", "id", Goods.class);
		// Composite Primary Key order: goods,projects
		arp.addMapping("goods_project", "goods,projects", GoodsProject.class);
		// Composite Primary Key order: goods,promotions
		arp.addMapping("goods_promotion", "goods,promotions", GoodsPromotion.class);
		// Composite Primary Key order: goods,tags
		arp.addMapping("goods_tag", "goods,tags", GoodsTag.class);
		arp.addMapping("log", "id", Log.class);
		arp.addMapping("member", "id", Member.class);
		arp.addMapping("member_attribute", "id", MemberAttribute.class);
		// Composite Primary Key order: favorite_goods,favorite_members
		arp.addMapping("member_favorite_goods", "favorite_goods,favorite_members", MemberFavoriteGoods.class);
		arp.addMapping("member_rank", "id", MemberRank.class);
		arp.addMapping("message", "id", Message.class);
		arp.addMapping("message_config", "id", MessageConfig.class);
		arp.addMapping("navigation", "id", Navigation.class);
		arp.addMapping("order", "id", Order.class);
		arp.addMapping("order_item", "id", OrderItem.class);
		arp.addMapping("order_log", "id", OrderLog.class);
		arp.addMapping("parameter", "id", Parameter.class);
		arp.addMapping("payment", "id", Payment.class);
		arp.addMapping("payment_log", "id", PaymentLog.class);
		arp.addMapping("payment_method", "id", PaymentMethod.class);
		arp.addMapping("permission", "id", Permission.class);
		// Composite Primary Key order: permissions,roles
		arp.addMapping("permission_role", "permissions,roles", PermissionRole.class);
		arp.addMapping("plugin_config", "id", PluginConfig.class);
		arp.addMapping("point_log", "id", PointLog.class);
		arp.addMapping("product", "id", Product.class);
		arp.addMapping("product_category", "id", ProductCategory.class);
		// Composite Primary Key order: brands,product_categories
		arp.addMapping("product_category_brand", "brands,product_categories", ProductCategoryBrand.class);
		// Composite Primary Key order: product_categories,promotions
		arp.addMapping("product_category_promotion", "product_categories,promotions", ProductCategoryPromotion.class);
		arp.addMapping("product_notify", "id", ProductNotify.class);
		arp.addMapping("promotion", "id", Promotion.class);
		// Composite Primary Key order: coupons,promotions
		arp.addMapping("promotion_coupon", "coupons,promotions", PromotionCoupon.class);
		// Composite Primary Key order: gift_promotions,gifts
		arp.addMapping("promotion_gift", "gift_promotions,gifts", PromotionGift.class);
		// Composite Primary Key order: member_ranks,promotions
		arp.addMapping("promotion_member_rank", "member_ranks,promotions", PromotionMemberRank.class);
		arp.addMapping("receiver", "id", Receiver.class);
		arp.addMapping("refunds", "id", Refunds.class);
		arp.addMapping("returns", "id", Returns.class);
		arp.addMapping("returns_item", "id", ReturnsItem.class);
		arp.addMapping("review", "id", Review.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("seo", "id", Seo.class);
		arp.addMapping("shipping", "id", Shipping.class);
		arp.addMapping("shipping_item", "id", ShippingItem.class);
		arp.addMapping("shipping_method", "id", ShippingMethod.class);
		// Composite Primary Key order: payment_methods,shipping_methods
		arp.addMapping("shipping_payment_method", "payment_methods,shipping_methods", ShippingPaymentMethod.class);
		arp.addMapping("sms", "id", Sms.class);
		arp.addMapping("sn", "id", Sn.class);
		arp.addMapping("specification", "id", Specification.class);
		arp.addMapping("statistic", "id", Statistic.class);
		arp.addMapping("stock_log", "id", StockLog.class);
		arp.addMapping("tag", "id", Tag.class);
	}
}

