package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseGoodsProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsProject extends BaseGoodsProject<GoodsProject> {
	public static final GoodsProject dao = new GoodsProject().dao();
}
